"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.View = exports.TouchableWithoutFeedback = exports.TouchableOpacity = exports.TouchableNativeFeedback = exports.TouchableHighlight = exports.Text = exports.TextInput = exports.Switch = exports.StatusBar = exports.SnapshotViewIOS = exports.SectionList = exports.ScrollView = exports.RefreshControl = exports.Modal = exports.KeyboardAvoidingView = exports.InputAccessoryView = exports.Image = exports.FlatList = exports.DrawerLayoutAndroid = exports.Button = exports.ActivityIndicator = void 0;
var react_native_1 = require("react-native");
var helper_1 = require("./helper");
exports.ActivityIndicator = helper_1.makeHelper(react_native_1.ActivityIndicator);
exports.Button = helper_1.makeHelper(react_native_1.Button);
exports.DrawerLayoutAndroid = helper_1.makeHelper(react_native_1.DrawerLayoutAndroid);
exports.FlatList = helper_1.makeHelper(react_native_1.FlatList);
exports.Image = helper_1.makeHelper(react_native_1.Image);
exports.InputAccessoryView = helper_1.makeHelper(react_native_1.InputAccessoryView);
exports.KeyboardAvoidingView = helper_1.makeHelper(react_native_1.KeyboardAvoidingView);
exports.Modal = helper_1.makeHelper(react_native_1.Modal);
exports.RefreshControl = helper_1.makeHelper(react_native_1.RefreshControl);
exports.ScrollView = helper_1.makeHelper(react_native_1.ScrollView);
exports.SectionList = helper_1.makeHelper(react_native_1.SectionList);
exports.SnapshotViewIOS = helper_1.makeHelper(react_native_1.SnapshotViewIOS);
exports.StatusBar = helper_1.makeHelper(react_native_1.StatusBar);
exports.Switch = helper_1.makeHelper(react_native_1.Switch);
exports.TextInput = helper_1.makeHelper(react_native_1.TextInput);
exports.Text = helper_1.makeHelper(react_native_1.Text);
exports.TouchableHighlight = helper_1.makeHelper(react_native_1.TouchableHighlight);
exports.TouchableNativeFeedback = helper_1.makeHelper(react_native_1.TouchableNativeFeedback);
exports.TouchableOpacity = helper_1.makeHelper(react_native_1.TouchableOpacity);
exports.TouchableWithoutFeedback = helper_1.makeHelper(react_native_1.TouchableWithoutFeedback);
exports.View = helper_1.makeHelper(react_native_1.View);
//# sourceMappingURL=components.js.map