import { ActivityIndicator as _ActivityIndicator, Button as _Button, DrawerLayoutAndroid as _DrawerLayoutAndroid, FlatList as _FlatList, Image as _Image, InputAccessoryView as _InputAccessoryView, KeyboardAvoidingView as _KeyboardAvoidingView, Modal as _Modal, RefreshControl as _RefreshControl, ScrollView as _ScrollView, SectionList as _SectionList, SnapshotViewIOS as _SnapshotViewIOS, StatusBar as _StatusBar, Switch as _Switch, TextInput as _TextInput, Text as _Text, TouchableHighlight as _TouchableHighlight, TouchableNativeFeedback as _TouchableNativeFeedback, TouchableOpacity as _TouchableOpacity, TouchableWithoutFeedback as _TouchableWithoutFeedback, View as _View, } from 'react-native';
import { makeHelper } from './helper';
export var ActivityIndicator = makeHelper(_ActivityIndicator);
export var Button = makeHelper(_Button);
export var DrawerLayoutAndroid = makeHelper(_DrawerLayoutAndroid);
export var FlatList = makeHelper(_FlatList);
export var Image = makeHelper(_Image);
export var InputAccessoryView = makeHelper(_InputAccessoryView);
export var KeyboardAvoidingView = makeHelper(_KeyboardAvoidingView);
export var Modal = makeHelper(_Modal);
export var RefreshControl = makeHelper(_RefreshControl);
export var ScrollView = makeHelper(_ScrollView);
export var SectionList = makeHelper(_SectionList);
export var SnapshotViewIOS = makeHelper(_SnapshotViewIOS);
export var StatusBar = makeHelper(_StatusBar);
export var Switch = makeHelper(_Switch);
export var TextInput = makeHelper(_TextInput);
export var Text = makeHelper(_Text);
export var TouchableHighlight = makeHelper(_TouchableHighlight);
export var TouchableNativeFeedback = makeHelper(_TouchableNativeFeedback);
export var TouchableOpacity = makeHelper(_TouchableOpacity);
export var TouchableWithoutFeedback = makeHelper(_TouchableWithoutFeedback);
export var View = makeHelper(_View);
//# sourceMappingURL=components.js.map